name = "bulk-overrides"
type = "javascript"

[env.staging]
name = "staging-overrides"
vars = { ENVIRONMENT = "staging" }
workers_dev = true
kv_namespaces = [
         { binding = "override_variables", id = "0c01ea38e588421f9b5dd816bc18c5a9" }
]

[env.prod]
name = "prod-overrides"
vars = { ENVIRONMENT = "production" }
route = "*test.erfianugrah.com/*"
kv_namespaces = [
         { binding = "override_variables", id = "0c01ea38e588421f9b5dd816bc18c5a9" }
]